USE [master]
GO

/****** Object:  Database [TechTestDB]    Script Date: 23-Oct-18 3:56:35 AM ******/
CREATE DATABASE [TechTestDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TechTestDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\TechTestDB.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TechTestDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\TechTestDB_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TechTestDB] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TechTestDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TechTestDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TechTestDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TechTestDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TechTestDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TechTestDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [TechTestDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TechTestDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [TechTestDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TechTestDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TechTestDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TechTestDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TechTestDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TechTestDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TechTestDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TechTestDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TechTestDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TechTestDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TechTestDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TechTestDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TechTestDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TechTestDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TechTestDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TechTestDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TechTestDB] SET RECOVERY FULL 
GO

ALTER DATABASE [TechTestDB] SET  MULTI_USER 
GO

ALTER DATABASE [TechTestDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TechTestDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TechTestDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TechTestDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TechTestDB] SET  READ_WRITE 
GO

USE [TechTestDB]
GO

/****** Object:  Table [dbo].[GLHeader]    Script Date: 23-Oct-18 3:43:20 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Employee] (
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](60) NOT NULL,
	[LastName] [nvarchar](60) NOT NULL,
	[Department] [nvarchar](100) NOT NULL,
	[Salary] [float] NOT NULL
 CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO